### ISSUE TITLE
Add these survey as well

### ISSUE THREAD

**Issue by azalahmadkhan** [youngfish42/Awesome-Federated-Learning-on-Graph-and-Tabular-Data#23]
Towards Personalized Federated Learning - https://arxiv.org/pdf/2103.00710.pdf
Three Approaches for Personalization with Applications to Federated Learning - https://arxiv.org/pdf/2002.10619.pdf

**Comment by youngfish42** [comment]
Thanks for your suggestion

**Comment by azalahmadkhan** [comment]
Thanks
